
version: '3'

services:
    mysql:
        image: mysql:5.6
        #ports:
        #    - "3306:3306"
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./mysql:/var/lib/mysql
            - ./mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
            - ./mysql/query.log:/var/log/mysql/query.log
            - ./mysql/slow.log:/var/log/mysql/slow.log
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_use_native_aio=1
        networks:
            - vpcbr
    tars:
        image: tarscloud/tars
        ports:
            - "7022:3001" #帐号管理
            - "7023:3000" #控制台
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - MYSQL_HOST=mysql
            - MYSQL_ROOT_PASSWORD=password
            - DBIP=mysql
            - DBPort=3306
            - DBUser=root
            - DBPassword=password
            - DBTarsPass=tarspass
            - MOUNT_DATA=true
        volumes:
            - ./tars:/data
        depends_on:
            - mysql
        networks:
            vpcbr:
                ipv4_address: 10.5.1.1
    tarsnode:
        image: tarscloud/tars-node:dev
        ports:
            - "7400:3000"
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - WEB_HOST=tars:3000
            - DBIP=mysql
            - DBPort=3306
            - MOUNT_DATA=true
            - MASTER=tars
            - SLAVE=true
        volumes:
            - ./tarsnode:/data
        depends_on:
            - tars
            - tarsnode_101
            - tarsnode_102
        networks:
            vpcbr:
                ipv4_address: 10.5.1.100 #10.5.1.0/24给tars集群
    tarsnode_101:
        image: tarscloud/tars-node:dev
        ports:
            - "7401:3000"
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - WEB_HOST=tars:3000
            - DBIP=mysql
            - DBPort=3306
            - MOUNT_DATA=true
            - MASTER=tars
            - SLAVE=true
        volumes:
            - ./tarsnode:/data
        depends_on:
            - tars
        networks:
            vpcbr:
                ipv4_address: 10.5.1.101 #10.5.1.0/24给tars集群
    tarsnode_102:
        image: tarscloud/tars-node:dev
        ports:
            - "7402:3000"
        restart: always
        environment:
            - TZ=Asia/Shanghai
            - WEB_HOST=tars:3000
            - DBIP=mysql
            - DBPort=3306
            - MOUNT_DATA=true
            - MASTER=tars
            - SLAVE=true
        volumes:
            - ./tarsnode:/data
        depends_on:
            - tars
        networks:
            vpcbr:
                ipv4_address: 10.5.1.102 #10.5.1.0/24给tars集群
networks:
    vpcbr:
        driver: bridge
        ipam:
            config:
                - subnet: 10.5.0.0/16
